authentication:
    ClientID: <PUT CLIENT ID HERE>
    ClientSecret: <PUT CLIENT  SECRET HERE>


session:
    secretKey: randomSecretKeyHere

frontend-redirect: "/loginRedirect.html"
frontend-host: ""

workspaces-location: "~/son-editor/workspaces/"

allowed-hosts:
  - "localhost"
database:
    location: "production.db"
testing: False

#uncomment and configure to enable web configuration
#config:
#  pwd: admin
#  user: admin

# URL to sonata schemas
schemas:
  - name: SONATA NFV
    url: https://raw.githubusercontent.com/sonata-nfv/son-schema/master/
